name: "CLA assistant lite bot"
on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened,closed,synchronize]
    
jobs:
  CLAassistant:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "CLA Assistant"
      if: (github.event.comment.body == 'recheckcla' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request'
      # Alpha Release
      uses: cla-assistant/github-action@refactor
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with: 
        path-to-signatures: '.github/signatures/version2/cla.json'
        path-To-cladocument: 'https://github.com/Flank/flank/blob/master/cla.md'
        branch: 'master'
        whitelist: user1,user2,bot*
        empty-commit-flag: false
        blockchain-storage-flag: false
