name: Test Workflow

on:
  pull_request:
    types: [opened,synchronize ]

jobs:
  build:
    

    runs-on: ubuntu-latest

    steps:
    - name: Post Issue comment
      uses: cla-assistant-akshayib/commentcreator@master

      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        message: 'Thank you very much. Please fork this repository and raise the PR when ready '
